### ISSUE TITLE
Provide guide for setting up Spark-Cassandra connector

### ISSUE THREAD

**Issue by sdanielzafar** [AkhilNairAmey/crassy#3]
Hopefully this will be fast- 

It seems like the [Spark Packages site](https://spark-packages.org/package/datastax/spark-cassandra-connector) this the best place to get the connector. I've tried downloading the `.jar` based on this [compatibility table](https://github.com/datastax/spark-cassandra-connector/blob/master/README.md). There are three "How To" options at the site:
1. Call the package with spark-shell, pyspark, or spark-submit. 
2. Use SBT
3. Use Maven

I don't have `sbt` or `mvn` installed, and other R users may not either. It seems like adding it to the `config.yml` is needed, but where do we put the file so that it calls it from the `.yml`? Also, should we instruct to download the `jar` or the `zip`? Do users need to build for assembly `jar` and artifacts as described [here](https://github.com/datastax/spark-cassandra-connector/blob/master/doc/12_building_and_artifacts.md)?

Thanks!

**Comment by AkhilGNair** [comment]
None of this is necessary as `sparklyr` will handle the entire spark set up for you.  No building of `jar`s is necessary as the version specific spark-cassandra-connectors are available as prebuilt on the default package repository `sparklyr` looks for packages in.

For example, if in my `config.yml` I specify 
```
default:
  sparklyr.defaultPackages:
    - com.amazonaws:aws-java-sdk-pom:1.10.34,com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3
```
Then R will attempt to submit the job such that the dependency is resolved.  In the log file:
```
Ivy Default Cache set to: /home/akhil/.ivy2/cache
The jars for the packages stored in: /home/akhil/.ivy2/jars
:: loading settings :: url = jar:file:/home/akhil/.cache/spark/spark-2.0.2-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.datastax.spark#spark-cassandra-connector_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found com.datastax.spark#spark-cassandra-connector_2.11;2.0.0-M3 in central
	found io.netty#netty-all;4.0.33.Final in central
	found commons-beanutils#commons-beanutils;1.8.0 in central
	found joda-time#joda-time;2.3 in central
	found com.twitter#jsr166e;1.1.0 in central
	found org.joda#joda-convert;1.2 in central
	found org.scala-lang#scala-reflect;2.11.8 in central
:: resolution report :: resolve 298ms :: artifacts dl 10ms
	:: modules in use:
	com.datastax.spark#spark-cassandra-connector_2.11;2.0.0-M3 from central in [default]
	com.twitter#jsr166e;1.1.0 from central in [default]
	commons-beanutils#commons-beanutils;1.8.0 from central in [default]
	io.netty#netty-all;4.0.33.Final from central in [default]
	joda-time#joda-time;2.3 from central in [default]
	org.joda#joda-convert;1.2 from central in [default]
	org.scala-lang#scala-reflect;2.11.8 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   7   |   0   |   0   |   0   ||   7   |   0   |
	---------------------------------------------------------------------
```

The above log has been produced by the code given in the README which is < 20 lines - no other set up is necessary as the `sparklyr` guys have done an amazing job.  I outlined the recommended directory structure and method of setting dependencies/config in #2.  

It's much simpler than you think! The only room for error is mis-versioning between the connector and spark, as the table you link to specifies.

**Comment by sdanielzafar** [comment]
Ok I'm still missing something-

```
library(sparklyr)
library(dplyr)
library(crassy)

sc <- spark_connect(master = "local", 
                    spark_home = "/var/lib/Spark", 
                    version = "2.1.1", 
                    hadoop_version = "2.7")

test = spark_load_cassandra_table(
  sc            = sc,
  cass_keyspace = "test_spark", 
  cass_tbl      = "test", 
  spk_tbl_name  = "test"
)
```

Here is `config.yml`:

```
default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  spark.sql.shuffle.partitions.local: !expr parallel::detectCores()
  spark.env.SPARK_LOCAL_IP.local: 127.0.0.1
  spark.cassandra.connection.host: 127.0.0.1
  
  # include the embedded csv package for spark 1.x
  sparklyr.csv.embedded: "^1.*"

  # default spark packages to load
  sparklyr.defaultPackages: com.datastax.spark:spark-cassandra-connector_2.11:2.0.1

  # command line arguments to spark-shell
  # sparklyr.shell.*
  sparklyr.shell.driver-class-path: !expr Sys.getenv("SPARK_DRIVER_CLASSPATH")
```

Here is my Cassandra table:
```
cqlsh> select * from test_spark.test;

 value
-------
     1

(1 rows)
```
Here is the schema:
```
cqlsh> describe test_spark.test

CREATE TABLE test_spark.test (
    value int PRIMARY KEY
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
```
The error only comes when I do this:
```
> test
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1, localhost, executor driver): java.lang.NoClassDefFoundError: com/datastax/spark/connector/rdd/CassandraLimit$$anonfun$limitForIterator$1
	at com.datastax.spark.connector.rdd.CassandraLimit$.limitForIterator(CassandraLimit.scala:21)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:368)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1951)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:275)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2386)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2385)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2392)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2420)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2419)
	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2801)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/datastax/spark/connector/rdd/CassandraLimit$$anonfun$limitForIterator$1
	at com.datastax.spark.connector.rdd.CassandraLimit$.limitForIterator(CassandraLimit.scala:21)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:368)
```

**Comment by AkhilGNair** [comment]
Couple of things - 
  1) You've added the Cassandra driver core as a dependency INSTEAD of the cassandra-spark-connector
  2) You're explicit choosing a different directory in the `spark_home` argument

To rectify 1) specify the cassandra package I noted above, and 2) might not be an issue, but I would be tempted to just let `sparklyr` handle everything, i.e. install spark with `sparklyr::spark_install()` and set `spark_home = sparklyr::spark_home_dir()`

**Comment by sdanielzafar** [comment]
Eeek, sorry I've been tinkering with this too much. I've updated the above. I have 2 versions of Spark installed, one in the specified `/var/lib/Spark` and one that SparklyR installed. I chose to make my own install and connect it there because so that it would be easier to run across the cluster. I've heard that `spark_home` must be identical across the cluster and was attempting to standardize. Very much open to doing it all with Sparklyr as long as I can easily set up common `spark_home`. Since this isn't working I'll start working from this angle.

**Comment by sdanielzafar** [comment]
It set `spark_home` as such:
```
> sparklyr::spark_home_dir()
[1] "/dzafar/.cache/spark/spark-2.1.0-bin-hadoop2.7"
```
So other users will not be able to access. I think that's reason why folks would need to set a custom home dir.

**Comment by AkhilGNair** [comment]
Type `sc` into your terminal and check where you can find the output log file. See where it's storing the dependencies, and check it's in the appropriate place for the directory you specify.

Also, before trying to set this up in the cluster case, try and set it up in the single node case to simplify things. Does the single node case with the sparklyr spark install throw an error? If not, try and work out the key difference between the sparklyr spark install case, and your `/var/lib/Spark` case.

**Comment by sdanielzafar** [comment]
Ah finally figured out what was wrong. A coworker had built an assembly `jar` from the wrong Scala version and put it in my `jars` file. So glad that's over. I'll get you something to pull, turns out all you need is to have the connector in your `jars` folder, not required to have it in the `config.yml` that you re-make for every `.Rproj`. Thanks for all your help 👍 I'll get that pull request in a second.

**Comment by AkhilGNair** [comment]
You _can_ just put it in the jars folder but note that is is not recommended as then the application depends on the user's system, instead of the project.  Given rstudio provides an easy way to contain all the configuration within the project, making ad hoc changes to the system is in general bad practice.

For example, the problem you describe above would not have happened if your spark folder was treated as ephemeral, and you were confident you could safely scrape and reinstall it as all the config was self-contained.

**Comment by sdanielzafar** [comment]
I see what you are saying, but for a server with many users (with various levels of expertise) and scripts not leaving that server, I think just loading the jar will be easiest as users won't have to learn how to make `yml` and Spark-Cassandra-Connector methods will ostensibly be part of the Spark API. Also this ensures that any Spark configuration options are global across users on the server instead of each user having to both install and configure Spark separately. Generally I agree that the `yml` or package specification method is great for scenarios outside of this narrow use-case.

**Comment by AkhilGNair** [comment]
Well thought out! Seems to be the right soln in your case :).  Thanks for the PR. I'll edit and pull in soon when I have a chance.

I might remove the limit functionality such that it can be added to a different PR for better compartmentalisation.  I also noticed you didn't add a test for it - have you ever done any unit testing before?

**Comment by sdanielzafar** [comment]
I'd definitely recommend not including that `limit` commit in your pull. No I haven't done tests before. Feel free to point me to any guides you find useful, but I can probably just Google it :)
